language: php

addons:
  chrome: stable
  apt:
    packages:
    - nginx

sudo: false

# Test main supported versions of PHP against latest WP.
php:
- 5.6

env:
- WP_VERSION=latest WP_MULTISITE=0

# Additional tests against stable PHP (min recommended version is 5.6) and past supported versions of WP
# and code coverage report.
matrix:
  fast_finish: true
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_PHPCS=1 RUN_E2E=1

script:
  - bash mysql --version