<?php

namespace Objectiv\Plugins\Checkout\Compatibility\Gateways;

use Objectiv\Plugins\Checkout\Compatibility\Base;

class KlarnaPayments extends Base {

	protected $klarna = null;

	protected $klarna_gateway = null;

	protected $klarna_id = "klarna_payments";

	public function __construct() {
		parent::__construct();
	}

	function is_available() {
		$is_available = false;

		// If the Karna main class exists
		if ( class_exists( '\\WC_Klarna_Payments' ) ) {
			$available_gateways = WC()->payment_gateways->get_available_payment_gateways();
			$klarna_gateway     = $available_gateways[ $this->klarna_id ] ?: null;

			// If the gateway is not null
			if ( $klarna_gateway ) {
				// Get the gateway availability and set it
				$is_available = $klarna_gateway->is_available();

				$this->klarna_gateway = $klarna_gateway;
			}
		}

		return $is_available;
	}

	function allowed_scripts( $scripts ) {
		$scripts[] = 'klarna_payments';
		return $scripts;
	}

	function allowed_styles( $styles ) {
		return parent::allowed_styles( $styles ); // TODO: Change the autogenerated stub
	}
}